export const ROUTES = {
  LOGIN:            '/login',
  FORGOT_PASSWORD:  '/forgot-password',
  RESET_PASSWORD:   '/reset-password',
  DASHBOARD: '/dashboard',
  ATTENDANCE: '/attendance',
  LEAVE: '/leave',
  PROJECTS:        '/projects',
  PROJECT_DETAIL:  '/projects/:id',
  TASKS: '/tasks',
  STAFF: '/staff',
  PAYROLL: '/payroll',
  REPORTS: '/reports',
  SETTINGS: '/settings',
  PROFILE: '/profile',
} as const
